/// Sabit dil listesi (Toplam 23: Tümü İngilizce ismine göre alfabetik dizilidir, ilk 3 istisna: TR, AZ, TM)
const List<Map<String, String>> supportedLanguages = [
  {'code': 'tr', 'name': 'Türkçe', 'flag': '🇹🇷'},
  {'code': 'az', 'name': 'Azərbaycanca', 'flag': '🇦🇿'},
  {'code': 'tk', 'name': 'Türkmen dili', 'flag': '🇹🇲'},
  {'code': 'ar', 'name': 'العربية (Arabic)', 'flag': '🇸🇦'},
  {'code': 'bn', 'name': 'বাংলা (Bengali)', 'flag': '🇧🇩'},
  {'code': 'zh', 'name': '中文 (Chinese)', 'flag': '🇨🇳'},
  {'code': 'en', 'name': 'English', 'flag': '🇬🇧'},
  {'code': 'fr', 'name': 'Français (French)', 'flag': '🇫🇷'},
  {'code': 'de', 'name': 'Deutsch (German)', 'flag': '🇩🇪'},
  {'code': 'hi', 'name': 'हिन्दी (Hindi)', 'flag': '🇮🇳'},
  {'code': 'id', 'name': 'Bahasa Indonesia', 'flag': '🇮🇩'},
  {'code': 'it', 'name': 'Italiano (Italian)', 'flag': '🇮🇹'},
  {'code': 'ja', 'name': '日本語 (Japanese)', 'flag': '🇯🇵'},
  {'code': 'ko', 'name': '한국어 (Korean)', 'flag': '🇰🇷'},
  {'code': 'mr', 'name': 'मराठी (Marathi)', 'flag': '🇮🇳'},
  {'code': 'pt', 'name': 'Português (Portuguese)', 'flag': '🇵🇹'},
  {'code': 'ru', 'name': 'Русский (Russian)', 'flag': '🇷🇺'},
  {'code': 'es', 'name': 'Español (Spanish)', 'flag': '🇪🇸'},
  {'code': 'ta', 'name': 'தமிழ் (Tamil)', 'flag': '🇮🇳'},
  {'code': 'te', 'name': 'తెలుగు (Telugu)', 'flag': '🇮🇳'},
  {'code': 'ur', 'name': 'اردو (Urdu)', 'flag': '🇵🇰'},
  {'code': 'vi', 'name': 'Tiếng Việt (Vietnamese)', 'flag': '🇻🇳'},
];

/// Sabit ülke listesi (Toplam 41: İlk 3 TR, AZ, TM. Gerisi alfabetik)
const List<Map<String, String>> supportedCountries = [
  {'code': 'TR', 'name': 'Turkey', 'flag': '🇹🇷'},
  {'code': 'AZ', 'name': 'Azerbaijan', 'flag': '🇦🇿'},
  {'code': 'TM', 'name': 'Turkmenistan', 'flag': '🇹🇲'},
  {'code': 'DZ', 'name': 'Algeria', 'flag': '🇩🇿'},
  {'code': 'AR', 'name': 'Argentina', 'flag': '🇦🇷'},
  {'code': 'BD', 'name': 'Bangladesh', 'flag': '🇧🇩'},
  {'code': 'BR', 'name': 'Brazil', 'flag': '🇧🇷'},
  {'code': 'CA', 'name': 'Canada', 'flag': '🇨🇦'},
  {'code': 'CN', 'name': 'China', 'flag': '🇨🇳'},
  {'code': 'CO', 'name': 'Colombia', 'flag': '🇨🇴'},
  {'code': 'CD', 'name': 'DR Congo', 'flag': '🇨🇩'},
  {'code': 'EG', 'name': 'Egypt', 'flag': '🇪🇬'},
  {'code': 'ET', 'name': 'Ethiopia', 'flag': '🇪🇹'},
  {'code': 'FR', 'name': 'France', 'flag': '🇫🇷'},
  {'code': 'DE', 'name': 'Germany', 'flag': '🇩🇪'},
  {'code': 'IN', 'name': 'India', 'flag': '🇮🇳'},
  {'code': 'ID', 'name': 'Indonesia', 'flag': '🇮🇩'},
  {'code': 'IR', 'name': 'Iran', 'flag': '🇮🇷'},
  {'code': 'IQ', 'name': 'Iraq', 'flag': '🇮🇶'},
  {'code': 'IT', 'name': 'Italy', 'flag': '🇮🇹'},
  {'code': 'JP', 'name': 'Japan', 'flag': '🇯🇵'},
  {'code': 'KE', 'name': 'Kenya', 'flag': '🇰🇪'},
  {'code': 'MX', 'name': 'Mexico', 'flag': '🇲🇽'},
  {'code': 'MA', 'name': 'Morocco', 'flag': '🇲🇦'},
  {'code': 'MM', 'name': 'Myanmar', 'flag': '🇲🇲'},
  {'code': 'NG', 'name': 'Nigeria', 'flag': '🇳🇬'},
  {'code': 'PK', 'name': 'Pakistan', 'flag': '🇵🇰'},
  {'code': 'PH', 'name': 'Philippines', 'flag': '🇵🇭'},
  {'code': 'PL', 'name': 'Poland', 'flag': '🇵🇱'},
  {'code': 'RU', 'name': 'Russia', 'flag': '🇷🇺'},
  {'code': 'ZA', 'name': 'South Africa', 'flag': '🇿🇦'},
  {'code': 'KR', 'name': 'South Korea', 'flag': '🇰🇷'},
  {'code': 'ES', 'name': 'Spain', 'flag': '🇪🇸'},
  {'code': 'SD', 'name': 'Sudan', 'flag': '🇸🇩'},
  {'code': 'TZ', 'name': 'Tanzania', 'flag': '🇹🇿'},
  {'code': 'TH', 'name': 'Thailand', 'flag': '🇹🇭'},
  {'code': 'UG', 'name': 'Uganda', 'flag': '🇺🇬'},
  {'code': 'UA', 'name': 'Ukraine', 'flag': '🇺🇦'},
  {'code': 'GB', 'name': 'United Kingdom', 'flag': '🇬🇧'},
  {'code': 'US', 'name': 'United States', 'flag': '🇺🇸'},
  {'code': 'VN', 'name': 'Vietnam', 'flag': '🇻🇳'},
];
